# Generated by Django 4.0.3 on 2022-04-09 19:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0006_alter_expenses_options"),
    ]

    operations = [
        migrations.RenameField(
            model_name="expenses",
            old_name="total_amount",
            new_name="original_amount",
        ),
        migrations.AddField(
            model_name="expenses",
            name="final_amount",
            field=models.FloatField(
                default=models.FloatField(
                    default=0.01,
                    validators=[django.core.validators.MinValueValidator(0.01)],
                )
            ),
        ),
    ]
