# Generated by Django 4.0.3 on 2022-04-09 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0007_rename_total_amount_expenses_original_amount_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expenses",
            name="final_amount",
            field=models.FloatField(null=True),
        ),
    ]
