# Generated by Django 4.0.3 on 2022-04-09 19:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0009_alter_expenses_final_amount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expenses",
            name="final_amount",
            field=models.FloatField(
                default=0.01,
                validators=[django.core.validators.MinValueValidator(0.01)],
            ),
        ),
    ]
