# Generated by Django 4.0.3 on 2022-04-09 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0010_alter_expenses_final_amount"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="expenses",
            name="final_amount",
        ),
    ]
