# Generated by Django 4.0.3 on 2022-03-24 16:32

import base.models
from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Entry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "expense",
                    djongo.models.fields.EmbeddedField(
                        model_container=base.models.Expense
                    ),
                ),
                ("headline", models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name="Expense",
        ),
    ]
