# Generated by Django 4.0.3 on 2022-04-09 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0003_expenses_total_amount"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="expenses",
            options={},
        ),
        migrations.AlterOrderWithRespectTo(
            name="expenses",
            order_with_respect_to="user",
        ),
    ]
