# Generated by Django 4.0.3 on 2022-04-09 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0005_alter_expenses_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="expenses",
            options={"ordering": ["-created"]},
        ),
    ]
