# Generated by Django 4.0.3 on 2022-04-09 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0007_rename_total_amount_expenses_original_amount"),
    ]

    operations = [
        migrations.AddField(
            model_name="expenses",
            name="final_amount",
            field=models.FloatField(default=0.01),
        ),
        migrations.AlterField(
            model_name="expenses",
            name="final_currency",
            field=models.CharField(
                choices=[
                    ("USD", "USD"),
                    ("EUR", "EUR"),
                    ("BTC", "BTC"),
                    ("CHF", "CHF"),
                    ("GBP", "GBP"),
                    ("ARS", "ARS"),
                ],
                default="eur",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="expenses",
            name="original_currency",
            field=models.CharField(
                choices=[
                    ("USD", "USD"),
                    ("EUR", "EUR"),
                    ("BTC", "BTC"),
                    ("CHF", "CHF"),
                    ("GBP", "GBP"),
                    ("ARS", "ARS"),
                ],
                default="eur",
                max_length=10,
            ),
        ),
    ]
