# Generated by Django 4.0.3 on 2022-04-10 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0008_expenses_final_amount_alter_expenses_final_currency_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expenses",
            name="final_currency",
            field=models.CharField(
                choices=[
                    ("USD", "USD"),
                    ("EUR", "EUR"),
                    ("BTC", "BTC"),
                    ("CHF", "CHF"),
                    ("GBP", "GBP"),
                    ("ARS", "ARS"),
                ],
                default="EUR",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="expenses",
            name="original_currency",
            field=models.CharField(
                choices=[
                    ("USD", "USD"),
                    ("EUR", "EUR"),
                    ("BTC", "BTC"),
                    ("CHF", "CHF"),
                    ("GBP", "GBP"),
                    ("ARS", "ARS"),
                ],
                default="EUR",
                max_length=10,
            ),
        ),
    ]
