# Generated by Django 4.0.3 on 2022-04-10 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0009_alter_expenses_final_currency_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="expenses",
            name="email",
            field=models.EmailField(default=" ", help_text="Requerido", max_length=200),
        ),
    ]
