# Generated by Django 4.0.3 on 2022-04-10 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0010_expenses_email"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="expenses",
            name="email",
        ),
    ]
